# Generated by Django 4.2.3 on 2023-07-17 19:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=50)),
                ('organization_status', models.BooleanField(default=True)),
                ('organization_created', models.DateTimeField(auto_now_add=True)),
                ('organization_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('department_status', models.BooleanField(default=True)),
                ('department_created', models.DateTimeField(auto_now_add=True)),
                ('department_modified', models.DateTimeField(auto_now=True)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('academic_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_name', models.CharField(max_length=100)),
                ('academic_status', models.BooleanField(default=True)),
                ('academic_created', models.DateTimeField(auto_now_add=True)),
                ('academic_modified', models.DateTimeField(auto_now=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.department')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.organization')),
            ],
        ),
    ]
