# Generated by Django 4.2.3 on 2023-07-17 19:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_status', models.BooleanField(default=True)),
                ('course_created', models.DateTimeField(auto_now_add=True)),
                ('course_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Type',
            fields=[
                ('user_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type_name', models.CharField(max_length=100)),
                ('user_type_status', models.BooleanField(default=True)),
                ('user_type_created', models.DateTimeField(auto_now_add=True)),
                ('user_type_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='user_type',
            constraint=models.UniqueConstraint(fields=('user_type_name',), name='unique_user_type_name'),
        ),
        migrations.AddField(
            model_name='course',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.organization'),
        ),
    ]
