# Generated by Django 4.2.3 on 2023-07-17 20:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_course_user_type_user_type_unique_user_type_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_dni', models.IntegerField(unique=True)),
                ('user_password', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_dob', models.DateField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.user_type')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=100)),
                ('teahcer_email', models.EmailField(max_length=254)),
                ('teacher_status', models.BooleanField(default=True)),
                ('teacher_created', models.DateTimeField(auto_now_add=True)),
                ('teacher_modified', models.DateTimeField(auto_now=True)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.organization')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.user')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_status', models.BooleanField(default=True)),
                ('assignment_created', models.DateTimeField(auto_now_add=True)),
                ('assignment_modified', models.DateTimeField(auto_now=True)),
                ('academic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.academic')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.course')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.organization')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.teacher')),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('user_dni',), name='unique_user_dni'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('user_email',), name='unique_user_email'),
        ),
    ]
