# Generated by Django 4.2.3 on 2023-07-17 20:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0006_delete_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester_name', models.CharField(max_length=100)),
                ('semester_status', models.BooleanField(default=True)),
                ('semester_created', models.DateTimeField(auto_now_add=True)),
                ('semester_modified', models.DateTimeField(auto_now=True)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.organization')),
            ],
        ),
    ]
